In [10]:
import os
os.chdir('C:\\Users\\Usuario\\Desktop\\dna')

#base homosapiens
data1= open('EIt.txt', 'r')
data2= open('EIf.txt', 'r')
data3= open('IEt.txt', 'r')
data4= open('IEf.txt', 'r')
f1= data1.readlines()
f2= data2.readlines()
f3= data3.readlines()
f4= data4.readlines()
del(f1[0:4])
del(f2[0:4])
del(f3[0:4])
del(f4[0:4])
data=[]
targ=[]

for i in range(len(f1)):
    f1[i]= f1[i].split('): ')
for i in range(len(f1)):
    data.append(f1[i][1])
    targ.append(0)

for i in range(len(f3)):
    f3[i]= f3[i].split('): ')
for i in range(len(f3)):
    data.append(f3[i][1])
    targ.append(1)

for i in range(3000):
    f2[i]= f2[i].split(') : ')
for i in range(3000):
    data.append(f2[i][1])
    targ.append(2)
    
for i in range(3000):
    f4[i]= f4[i].split(') : ')
for i in range(3000):
    data.append(f4[i][1])
    targ.append(2)
d=[]
for i in range(len(data)):
    da=[]
    for j in range(len(data[i])-1):
        if data[i][j]=='A':
            da.append(0)
        elif data[i][j]=='C':
            da.append(1)
        elif data[i][j]=='G':
            da.append(2)
        elif data[i][j]=='T':
            da.append(3)
        else:
            da.append(8)
    d.append(da)
data1.close()
data2.close()
data3.close()
data4.close()

In [ ]:
#passando o arquivo para um list, com as classes convertidas para int, converte as series para int
f= data1.readlines()
for i in range(len(f)):
    f[i]= f[i].split(',')
for i in range(len(f)):
    del(f[i][1])
for i in range(len(f)):
    f[i][1]=f[i][1].split()[0]
c=[]
for i in range(len(f)):
    b=[]
    if f[i][0]=='EI':
        b.append(0)
    elif f[i][0]=='IE':
        b.append(1)
    elif f[i][0]=='N':
        b.append(2)
    a=[]
    for j in range(len(f[i][1])):
        if f[i][1][j]=='A':
            a.append(0)
        elif f[i][1][j]=='C':
            a.append(1)
        elif f[i][1][j]=='G':
            a.append(2)
        elif f[i][1][j]=='T':
            a.append(3)
        else:
            a.append(8)
    b.append(a)
    c.append(b)
cdata=[]
ctarg=[]

for i in range(len(c)):
    cdata.append(c[i][1])
    ctarg.append((c[i][0]))
    

In [11]:
#importando ferramentas
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import tree
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import SGDClassifier
from sklearn.gaussian_process import GaussianProcessClassifier


from sklearn.feature_selection import SelectFromModel

#ensemble
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

from sklearn.metrics import classification_report,confusion_matrix

In [64]:
print(len(d))
c0=0
c1=0
c2=0
for i in range(len(targ)):
    if targ[i] == 0:
        c0 = c0 + 1
    elif targ[i]==1:
        c1= c1 + 1
    elif targ[i]==2:
        c2= c2 + 1
print(c0,c1,c2)

11676
2796 2880 6000


In [65]:
len(targ)

11676

In [12]:
#Voting Classifier with weight, pesos definidos pela media da porcentagem de acerto de cada classe em uma 10-fold cross-validation
#primeiro separa a base em 90% treino,  10% para testes, de maneira que se repita 10 vezes, tendo testes para toda a base
class0 = d[0:2796]
class1 = d[2796:5676]
class2 = d[5676:11676]
class0T = targ[0:2796]
class1T = targ[2796:5676]
class2T = targ[5676:11676]

clf1 = SVC(gamma='auto')
clf2 = AdaBoostClassifier(n_estimators=100)
clf3 = tree.DecisionTreeClassifier()
clf4 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
VotingWithWeightsPredictions=[]
predictions0= []
predictions1= []
predictions2= []
i=0
while i<10:
    #separacao da base
    dataTeste= class0[int(i*len(class0)/10):int((i+1)*len(class0)/10)]+class1[int(i*len(class1)/10):int((i+1)*len(class1)/10)]+class2[int(i*len(class2)/10):int((i+1)*len(class2)/10)]
    c0= class0.copy()
    c1= class1.copy()
    c2= class2.copy()
    del(c0[int(i*len(class0)/10):int((i+1)*len(class0)/10)])
    del(c1[int(i*len(class1)/10):int((i+1)*len(class1)/10)])
    del(c2[int(i*len(class2)/10):int((i+1)*len(class2)/10)])
    data= c0 + c1 + c2
    targTeste= class0T[int(i*len(class0T)/10):int((i+1)*len(class0T)/10)]+class1T[int(i*len(class1T)/10):int((i+1)*len(class1T)/10)]+class2T[int(i*len(class2T)/10):int((i+1)*len(class2T)/10)]
    c0T= class0T.copy()
    c1T= class1T.copy()
    c2T= class2T.copy()
    del(c0T[int(i*len(class0T)/10):int((i+1)*len(class0T)/10)])
    del(c1T[int(i*len(class1T)/10):int((i+1)*len(class1T)/10)])
    del(c2T[int(i*len(class2T)/10):int((i+1)*len(class2T)/10)])
    targ= c0T + c1T + c2T
    
    #calculando os pesos, 10-fold cross-validation no conjunto de treino apenas
    j=0
    M1W= []      #list para armezar os pesos do modelo 1
    M2W= []
    M3W= []
    M4W= []
    while j<10:
        #Separacao do conjunto de treino em 10-fold 
        dataPTeste =c0[int(j*len(c0)/10):int((j+1)*len(c0)/10)]+c1[int(j*len(c1)/10):int((j+1)*len(c1)/10)]+c2[int(j*len(c2)/10):int((j+1)*len(c2)/10)]
        c0P= c0.copy()
        c1P= c1.copy()
        c2P= c2.copy()
        del(c0P[int(j*len(c0)/10):int((j+1)*len(c0)/10)])
        del(c1P[int(j*len(c1)/10):int((j+1)*len(c1)/10)])
        del(c2P[int(j*len(c2)/10):int((j+1)*len(c2)/10)])
        dataP = c0P + c1P + c2P
        targPTeste =c0T[int(j*len(c0T)/10):int((j+1)*len(c0T)/10)]+c1T[int(j*len(c1T)/10):int((j+1)*len(c1T)/10)]+c2T[int(j*len(c2T)/10):int((j+1)*len(c2T)/10)]
        c0TP= c0T.copy()
        c1TP= c1T.copy()
        c2TP= c2T.copy()
        del(c0TP[int(j*len(c0T)/10):int((j+1)*len(c0T)/10)])
        del(c1TP[int(j*len(c1T)/10):int((j+1)*len(c1T)/10)])
        del(c2TP[int(j*len(c2T)/10):int((j+1)*len(c2T)/10)])
        targP = c0TP + c1TP + c2TP
        
        #construcao dos modelos, predicao do teste
        clf1.fit(dataP,targP)
        clf2.fit(dataP,targP)
        clf3.fit(dataP,targP)
        clf4.fit(dataP,targP)
        
        T1=clf1.predict(dataPTeste)
        T2=clf2.predict(dataPTeste)
        T3=clf3.predict(dataPTeste)
        T4=clf4.predict(dataPTeste)
        
        #confusion matrix e calculo dos pesos por porcentagem de acerto dos palpites
        cm1 = confusion_matrix(targPTeste, T1)
        cm2 = confusion_matrix(targPTeste, T2)
        cm3 = confusion_matrix(targPTeste, T3)
        cm4 = confusion_matrix(targPTeste, T4)
        
        T1weights= [cm1[0][0]/(cm1[0][0] + cm1[1][0] + cm1[2][0]), cm1[1][1]/(cm1[0][1] + cm1[1][1] + cm1[2][1]), cm1[2][2]/(cm1[0][2] + cm1[1][2] + cm1[2][2])]
        T2weights= [cm2[0][0]/(cm2[0][0] + cm2[1][0] + cm2[2][0]), cm2[1][1]/(cm2[0][1] + cm2[1][1] + cm2[2][1]), cm2[2][2]/(cm2[0][2] + cm2[1][2] + cm2[2][2])]
        T3weights= [cm3[0][0]/(cm3[0][0] + cm3[1][0] + cm3[2][0]), cm3[1][1]/(cm3[0][1] + cm3[1][1] + cm3[2][1]), cm3[2][2]/(cm3[0][2] + cm3[1][2] + cm3[2][2])]
        T4weights= [cm4[0][0]/(cm4[0][0] + cm4[1][0] + cm4[2][0]), cm4[1][1]/(cm4[0][1] + cm4[1][1] + cm4[2][1]), cm4[2][2]/(cm4[0][2] + cm4[1][2] + cm4[2][2])]
        
        M1W.append(T1weights)
        M2W.append(T2weights)
        M3W.append(T3weights)
        M4W.append(T4weights)
        
        j= j+1
    #media dos pesos de cada modelo
    M1Wm =[0,0,0]
    M2Wm =[0,0,0]
    M3Wm =[0,0,0]
    M4Wm =[0,0,0]
    for v in range(len(M1W)):
        M1Wm[0] += M1W[v][0]
        M1Wm[1] += M1W[v][1]
        M1Wm[2] += M1W[v][2]
        M2Wm[0] += M2W[v][0]
        M2Wm[1] += M2W[v][1]
        M2Wm[2] += M2W[v][2]
        M3Wm[0] += M3W[v][0]
        M3Wm[1] += M3W[v][1]
        M3Wm[2] += M3W[v][2]
        M4Wm[0] += M4W[v][0]
        M4Wm[1] += M4W[v][1]
        M4Wm[2] += M4W[v][2]
    M1Wm= [M1Wm[0]/10, M1Wm[1]/10, M1Wm[2]/10]
    M2Wm= [M2Wm[0]/10, M2Wm[1]/10, M2Wm[2]/10]
    M3Wm= [M3Wm[0]/10, M3Wm[1]/10, M3Wm[2]/10]
    M4Wm= [M4Wm[0]/10, M4Wm[1]/10, M4Wm[2]/10]
    
    #fit model e votacao
    clf1.fit(data,targ)
    clf2.fit(data,targ)
    clf3.fit(data,targ)
    clf4.fit(data,targ)

    T1=clf1.predict(dataTeste)
    T2=clf2.predict(dataTeste)
    T3=clf3.predict(dataTeste)
    T4=clf4.predict(dataTeste)
    
    
    
    for k in range(len(targTeste)):
        predictClass= [0,0,0]
        predictClass[T1[k]]= predictClass[T1[k]] + M1Wm[T1[k]]
        predictClass[T2[k]]= predictClass[T2[k]] + M2Wm[T2[k]]
        predictClass[T3[k]]= predictClass[T3[k]] + M3Wm[T3[k]]
        predictClass[T4[k]]= predictClass[T4[k]] + M4Wm[T4[k]]
        if(targTeste[k]==0):
            predictions0.append(np.argmax(predictClass))
        if(targTeste[k]==1):
            predictions1.append(np.argmax(predictClass))
        if(targTeste[k]==2):
            predictions2.append(np.argmax(predictClass))
    
    i= i+1
VotingWithWeightsPredictions= predictions0 + predictions1 + predictions2
    
#Verificando a precisao
c0=0
p0=0
c1=0
p1=0
c2=0
p2=0
for j in range(len(targ)):
        if(targ[j]==0):
            if(targ[j]==VotingWithWeightsPredictions[j]):
                p0=p0+1
            c0= c0 +1
        if(targ[j]==1):
            if(targ[j]==VotingWithWeightsPredictions[j]):
                p1=p1+1
            c1= c1 +1
        if(targ[j]==2):
            if(targ[j]==VotingWithWeightsPredictions[j]):
                p2=p2+1
            c2= c2 +1

print("Accuracy: %0.2f  , ei: %0.2f , ie: %0.2f, n: %0.2f" % ((p0/c0+ p1/c1 + p2/c2)/3, p0/c0, p1/c1, p2/c2))
conf_mat = confusion_matrix(targ, VotingWithWeightsPredictions)
print('Confusion:\n', conf_mat, '\n')

Accuracy: 0.82  , ei: 0.91 , ie: 0.75, n: 0.81


ValueError: Found input variables with inconsistent numbers of samples: [10508, 11676]

In [69]:
#Testes de algoritmos basicos na conversao numerica
clf=[]
nome=[]
cdata=d
ctarg= targ
clf.append(tree.DecisionTreeClassifier())
nome.append('Decision Tree')
clf.append(SVC(gamma='auto'))
nome.append('SVC Support Vector Machines')
clf.append(KNeighborsClassifier(n_neighbors=1))
nome.append('Nearest Neighbors1')
clf.append(GaussianNB())
nome.append('GaussianNB')
clf.append(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1))
nome.append('MLP classifier')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')
    
    
clf=[]
nome=[]
clf.append(tree.DecisionTreeClassifier())
nome.append('Decision Tree')
clf.append(SVC(gamma='auto'))
nome.append('SVC Support Vector Machines')
clf.append(KNeighborsClassifier(n_neighbors=1))
nome.append('Nearest Neighbors1')
clf.append(GaussianNB())
nome.append('GaussianNB')
clf.append(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1))
nome.append('MLP classifier')
print('BAGGING')
for i in range(len(clf)):
    bclf = BaggingClassifier(clf[i], max_samples=0.5, max_features=0.5)
    scores = cross_val_score(bclf, cdata, ctarg, cv=10)
    y_pred = cross_val_predict(bclf, cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')


print('random Forest')
clf = RandomForestClassifier(n_estimators=10)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

print('AdaBoost')
clf = AdaBoostClassifier(n_estimators=100)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

print('Gradient Tree Boosting')
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

print('Voting Classifier')
clf1 = SVC(gamma='auto')
clf2 = KNeighborsClassifier(n_neighbors=2)
clf3 = tree.DecisionTreeClassifier()
clf4 = GaussianNB()
clf = VotingClassifier(estimators=[('gbc', clf1), ('ada', clf2), ('DTc', clf3), ('gNB', clf4)], voting='hard')
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

Decision Tree 
Scores: [0.78938356 0.80479452 0.79023973 0.83133562 0.7859589  0.70804795
 0.72065124 0.70951157 0.73007712 0.71122536]
Accuracy: 0.76 (+/- 0.09) , ei: 0.80 , ie: 0.66, n: 0.78
Confusion:
 [[2232  162  402]
 [ 140 1914  826]
 [ 377  932 4691]] 

SVC Support Vector Machines 
Scores: [0.74571918 0.74486301 0.74743151 0.7885274  0.80650685 0.69606164
 0.72407883 0.68637532 0.77206512 0.73264781]
Accuracy: 0.74 (+/- 0.07) , ei: 0.75 , ie: 0.60, n: 0.81
Confusion:
 [[2099   93  604]
 [ 184 1730  966]
 [ 446  691 4863]] 

Nearest Neighbors1 
Scores: [0.43921233 0.42722603 0.45547945 0.44434932 0.43407534 0.46917808
 0.44215938 0.48157669 0.51071123 0.50214225]
Accuracy: 0.46 (+/- 0.06) , ei: 0.66 , ie: 0.41, n: 0.39
Confusion:
 [[1840  359  597]
 [ 866 1185  829]
 [2299 1348 2353]] 

GaussianNB 
Scores: [0.47003425 0.46232877 0.46232877 0.46318493 0.45719178 0.45119863
 0.46101114 0.46101114 0.46786632 0.46443873]
Accuracy: 0.46 (+/- 0.01) , ei: 0.94 , ie: 0.96, n: 0.00
Confu

In [9]:
clf=[]
nome=[]
cdata=d
ctarg= targ
print('Voting Classifier')
clf1 = SVC(gamma='auto')
clf2 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
clf3 = tree.DecisionTreeClassifier()
clf4 = AdaBoostClassifier(n_estimators=100)
clf = VotingClassifier(estimators=[('gbc', clf1), ('ada', clf2), ('DTc', clf3), ('gNB', clf4)], voting='hard')
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

Voting Classifier

Scores: [0.85359589 0.87414384 0.89811644 0.91267123 0.90239726 0.80222603
 0.8277635  0.80719794 0.83204799 0.82176521]
Accuracy: 0.85 (+/- 0.08) , ei: 0.94 , ie: 0.88, n: 0.80
Confusion:
 [[2618   35  143]
 [  99 2548  233]
 [ 408  803 4789]] 



In [7]:
data1.close()